### ISSUE TITLE
LUA error on game load in WoW Patch 11.0.2.56011 and BattlePetCount-11.0.2-20240813-1

### ISSUE THREAD

**Issue by fraerie** [GurliGebis/WoWAddon-BattlePetCountNG#10]
2x BattlePetCount/PetCard.lua:22: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@BattlePetCount/PetCard.lua"]:22: in function `Setup'
[string "@BattlePetCount/PetCard.lua"]:12: in function <BattlePetCount/PetCard.lua:11>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "BattlePetCount_PetCard"
 orderedModules = <table> {
 }
 enabledState = true
 baseName = "BattlePetCount"
 defaultModuleState = true
 moduleName = "PetCard"
}
(*temporary) = nil
(*temporary) = "Blizzard_Collections"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

**Comment by GurliGebis** [comment]
Thanks for reporting the issue.

I have pushed 11.0.2-20240814-1, which fixes the issue 🙂
