### ISSUE TITLE
Errors regarding missing Library

### ISSUE THREAD

**Issue by Yarvillian** [GurliGebis/WoWAddon-BattlePetCountNG#3]
Getting a strange error when loading into game everytime.
![missing library instance on login](https://github.com/GurliGebis/WoWAddon-BattlePetCountNG/assets/66763620/3dff8471-5857-4bf4-8923-844ed1e06b85)

**Comment by GurliGebis** [comment]
It is due to you installing the no-lib version of the addon.
If you download the "full" version, it will work.

The no-lib is for if you have the Ace3 library installed as a separate addon.
