### ISSUE TITLE
PR: Fix for the missing count for newer pet items

### ISSUE THREAD

**Issue by tflo** [GurliGebis/WoWAddon-BattlePetCountNG#5]
[This Issue belongs to [this PR](https://github.com/GurliGebis/WoWAddon-BattlePetCountNG/pull/4). You find additional info there.]

I was wondering why BPC was  not showing me the count of collected pets for the newer pet items (for example [Miloh](https://www.wowhead.com/item=205052/miloh), [Scout](https://www.wowhead.com/item=201441/scout),  [Petal](https://www.wowhead.com/item=200927/petal), etc.).

When I looked at the files, it became clear: BPC uses a fix table (`addon.Item2Species` in CritterItems.lua) to associate a species ID with an item ID. The newer items/species simply weren't added to this table.

So I guess I have good news for you (and for us users):

During BfA, Blizz added a new function to the API: [`GetPetInfoByItemID`](https://warcraft.wiki.gg/wiki/API_C_PetJournal.GetPetInfoByItemID)

Amongst many other things, this function also returns the species ID that is associated with the item, and we can get the species ID like this:

```lua
local speciesID = select(13, C_PetJournal.GetPetInfoByItemID(itemid))
```

I was unaware of this function too, and discovered it only recently in the context of another addon.

**This makes the whole `Item2Species` table obsolete, and you don't have to worry about adding new IDs to a list ever again.**

I have posted a [pull request](https://github.com/GurliGebis/WoWAddon-BattlePetCountNG/pull/4) for this.

Thanks for considering,

– Tom

**Comment by GurliGebis** [comment]
I have merged the PR, will make a new release for 10.2 in a few days, once I get time to test it.
